addons:
  ssh_known_hosts:
    - $DEPLOY_HOST
branches:
  only:
    - master
env:
  - DOCKER_COMPOSE_VERSION=3.9
before_install:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
    -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - cp .travis/id_rsa ~/.ssh/deploy_rsa
  - chmod 600 ~/.ssh/deploy_rsa
  - ssh-add ~/.ssh/deploy_rsa
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
    -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
script:
- DOCKER_HOST="ssh://$DEPLOY_USER@$DEPLOY_HOST" docker-compose up --build -d
- docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
- docker-compose push
