version: "3"

services:
  web:
    image: aneureka/push-to-kindle:latest
    build: .
    ports:
      - "8001:8001"
    volumes:
      - /tmp/push-to-kindle:/tmp/push-to-kindle/
    restart: unless-stopped
