version: '3'

volumes:
  uploads:

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8001"
    volumes:
      - uploads:/tmp/push-to-kindle/
    restart: unless-stopped
